language: cpp
os: windows
env:
  - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
script:
  - export PATH=$MSBUILD_PATH:$PATH
  - MSBuild.exe -help
  - MSBuild.exe LLWatch.sln /t:Rebuild /p:Configuration=Release
  - MSBuild.exe LLWatch.csproj /t:Clean /p:Configuration=Debug