language: cpp
os: windows
env:
  - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
script:
  - export PATH=$MSBUILD_PATH:$PATH
#  - MSBuild.exe -help
  - MSBuild.exe LLWatch.sln
#  - cd LLWatch
#  - MSBuild.exe LLWatch.vcxproj /t:Clean /p:Configuration=Release
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master